version: '3.8'

services:
  db:
    image: postgres:16
    container_name: trelloia-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trelloia-backend
    ports:
      - '3001:3000'
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata:
