# Imagem base leve com Node + Alpine Linux
FROM node:23-alpine

# Instala dependências úteis para o ambiente de desenvolvimento
RUN apk add --no-cache bash curl

# Habilita e prepara o pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de dependência
COPY package.json pnpm-lock.yaml ./

# Instala as dependências (sem gerar cache do pnpm)
RUN pnpm install

# Copia o restante do código do projeto
COPY . .

# Gera o Prisma Client (evita erros no dev)
RUN pnpm exec prisma generate

# Gera o Prisma Client (evita erros no dev)
RUN pnpm exec prisma generate

# Expõe a porta que o NestJS usará
EXPOSE 3000

# ⬇️ Executa migrations e inicia com hot reload
CMD ["sh", "-c", "pnpm exec prisma migrate deploy && pnpm start:dev"]

