name: Check Backend Before Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Instalar pnpm globalmente
        run: npm install -g pnpm

      - name: Instalar dependências
        run: pnpm install --frozen-lockfile

      - name: Verificar build
        run: pnpm build

      - name: Rodar testes
        run: pnpm test

      - name: Verificar formatação
        run: pnpm format --check
