name: Deploy Backend to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Prisma Generate
        run: npx prisma generate

      - name: Deploy to Railway
        uses: railwayapp/railway-action@v1
        with:
          serviceId: ${{ secrets.RAILWAY_SERVICE_ID }}
          projectId: ${{ secrets.RAILWAY_PROJECT_ID }}
          apiToken: ${{ secrets.RAILWAY_API_TOKEN }}
