name: Deploy Backend to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Ativar pnpm via Corepack
        run: corepack enable

      - name: Instalar dependências
        run: pnpm install --frozen-lockfile

      - name: Rodar testes
        run: pnpm test

      - name: Gerar Prisma Client
        run: npx prisma generate

      - name: Build do projeto
        run: pnpm build

      - name: Deploy para Railway
        uses: railwayapp/railway-action@v1
        with:
          serviceId: ${{ secrets.RAILWAY_SERVICE_ID }}
          projectId: ${{ secrets.RAILWAY_PROJECT_ID }}
          apiToken: ${{ secrets.RAILWAY_API_TOKEN }}
