name: Deploy Backend to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Railway
        uses: railwayapp/railway-up@v1
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
